workflows:
  healthflow-android-build:
    name: HealthFlow APK Release Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - main
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Clean build cache
        script: flutter clean
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your.email@gmail.com
        notify:
          success: true
          failure: true